mnec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wiki/', include('nec_wiki.urls')),
    url(r'^todo/', include('nec_todo.urls')),
    url(r'^calendar/', include('nec_calendar.urls')),
    url(r'^bank/', include('nec_bank.urls')),
    url(r'', include('nec.urls')),
    path(r'project/', include('project.urls')),
    path(r'store/', include('store.urls')),
]

nec/urls.py
"""Autogen for url."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^accounts/login/', auth_views.LoginView.as_view(), name='login',
        kwargs={'template_name': 'nec/login.html'}),
    url(r'^accounts/logout/', auth_views.LogoutView.as_view(), name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^accounts/signup/', views.signup, name='signup'),
    url(r'^bank/', views.bank, name='bank_index'),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_project/', views.CreateProjectView.as_view(), name='create_project'),
    path('detail_project/<int:pk>/', views.DetailProjectView.as_view(), name='detail_project'),
    path('create_projecttodo/<int:project_id>/<int:todo_id>/', views.create_project_todo, name='create_projecttodo'),
    path('delete_projecttodo/<int:todo_id>/', views.delete_project_todo, name='delete_projecttodo'),
    path('edit_projecttodo/<int:pk>/', views.EditProjectTodoView.as_view(), name='edit_projecttodo'),
    path('clear_projecttodo/<int:todo_id>/', views.clear_project_todo, name='clear_projecttodo'),
    path('add_priority_projecttodo/<int:todo_id>/<value>/', views.add_priority_projecttodo, name='add_priority_projecttodo'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('order_by/category_score', views.index_order_by_category_score, name='index_order_by_category_score'),
    path('detail/<int:pk>/', views.ItemDataDetailView.as_view(), name='detail_item'),
    path('clear_soldout/', views.clear_soldout, name='clear_soldout'),
    path('load_naver_data/', views.load_naver_data, name='load_naver_data'),
    path('load_naver_data/<int:load_count>/', views.load_naver_data, name='load_naver_data_limit'),
    path('load_domeme_data/', views.load_domeme_data, name='load_domeme_data'),
    path('load_naver_price/', views.load_naver_price, name='load_naver_price'),
    path('create_item/', views.create_item, name='create_item'),
    path('refresh_item/<int:pk>/', views.refresh_item_view, name='refresh_item'),
    path('refresh_uncorrect_margin/', views.refresh_uncorrect_margin, name='refresh_uncorrect_margin'),
    path('refresh_unset_naver_sale_price/', views.refresh_unset_naver_sale_price, name='refresh_unset_naver_sale_price'),
    path('refresh_uncorrect_upper_margin/', views.refresh_uncorrect_upper_margin, name='refresh_uncorrect_upper_margin'),
    path('title_replace_view/', views.title_replace_view, name='title_replace_view'),
    path('refresh_minimum_count_list/', views.refresh_minimum_count_list, name='refresh_minimum_count_list'),
    path('delete_duplicate_item/', views.delete_duplicate_item, name='delete_duplicate_item'),
    path('refresh_oldest/', views.refresh_oldest, name='refresh_oldest'),
    path('refresh_unset_naver_edit_id/', views.refresh_unset_naver_edit_id, name='refresh_unset_naver_edit_id'),
    path('title_replace_with_search/', views.title_replace_with_search, name='title_replace_with_search'),
    path('check_tag/', views.check_tag, name='check_tag'),
    path('reset_category_score/', views.reset_category_score, name='reset_category_score'),
    path('refresh_no_detail_page/', views.refresh_no_detail_page, name='refresh_no_detail_page'),
]

store/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.utils import timezone

from .models import ItemData, TitleReplace
from .domeme_parser import Domeme
from .naver_parser import Naver
from .scout_parser import Scout

# Create your views here.

# 세션에서 네이버 창과 도매매 창을 유지하려고 해보았으나, 세션을 저장하는 함수에서 json으로 시리얼라이즈를 하는데,
# 해당 작업에서 selenium 객체들을 시리얼라이즈하는데 실패함 serialize관련 내용을 추가하던가 해야할듯
# def get_domeme(request):
#     domeme = request.session.get('domeme')
#     if not domeme:
#         request.session['domeme'] = Domeme()
#         domeme = request.session['domeme']
#     return domeme

# def get_naver(request):
#     naver = request.session.get('naver')
#     if not naver:
#         request.session['naver'] = Naver()
#         naver = request.session['naver']
#     return naver

def get_domeme(request):
    return Domeme()

def get_naver(request):
    return Naver()

def get_index_dict(request, item_list):
    unset_sale_count = ItemData.objects.filter(user=request.user, naver_sale=0, domeme_row_price=-1).count()
    uncorrect_upper_margin = ItemData.objects.filter(user=request.user, margin_ratio__gt=25).order_by('-margin_ratio')
    unset_naver_edit_id = ItemData.objects.filter(user=request.user, naver_edit_id=-1)
    no_detail_page_count = ItemData.objects.filter(user=request.user, detail_page=-1).count()
    soldout_list = []
    return {'soldout_list':soldout_list, 'unset_sale_count':unset_sale_count, 'uncorrect_upper_margin':uncorrect_upper_margin, 'unset_naver_edit_id':unset_naver_edit_id, 'item_list':item_list,
            'no_detail_page_count':no_detail_page_count}

def index_view(request):
    item_list = ItemData.objects.filter(user=request.user).order_by('margin_ratio')
    return_dict = get_index_dict(request, item_list)
    return render(request, 'store/itemdata_list.html', return_dict)

def index_order_by_category_score(request):
    item_list = ItemData.objects.filter(user=request.user).order_by('-category_score')
    return_dict = get_index_dict(request, item_list)
    return render(request, 'store/itemdata_list.html', return_dict)

def reset_category_score(request):
    item_list = ItemData.objects.filter(user=request.user)
    for item in item_list:
        item.category_score = 99999
        item.save()

def detail_view(request, pk):
    return render(request, 'store/itemdata_detail.html')

class ItemDataDetailView(generic.DetailView):
    model = ItemData
        
def soldout_view(request, pk):
    return render(request, 'store/soldout_list.html')

def clear_soldout(request):
    domeme = get_domeme(request)
    domeme.clear_soldout()
    return redirect(reverse('store:index'))

def create_item(request):
    return redirect(reverse('store:index'))

''' 네이버에는 등록되었으나, 서버 디비에는 등록되지 않은 데이터를 가져온다. '''
def load_naver_data(request, load_count=0):
    item_list = ItemData.objects.filter(user=request.user)
    except_list = []
    for item in item_list:
        except_list.append(item.domeme_id)

    domeme = get_domeme(request)
    naver = get_naver(request)
    scout = Scout()
    naver_item_list = naver.get_sale_unset_item_list(except_list, depth=1, load_count=load_count)
    count = 0
    for naver_item in naver_item_list:
        process_print(count, len(naver_item_list))
        naver_item['user'] = request.user
        if naver_item['naver_sale'] == "-":
            naver_item['naver_sale'] = 0
        naver_item['title'] = title_replace(request.user, naver_item['title'])
        item = ItemData.objects.add_dict_item(naver_item)

        refresh_item(request, domeme, naver, item, depth=1, scout=scout)
        count = count + 1
    return redirect(reverse('store:index'))

def load_domeme_data(request):
    domeme = get_domeme(request)
    naver = get_naver(request)
    item_list = ItemData.objects.filter(user=request.user).order_by('-domeme_update_count', 'modify_date')
    
    count = 0
    start_time = timezone.now()
    for item in item_list:
        domeme_info = domeme.get_item_info(item.domeme_id)
        process_print(count, len(item_list))
        print("업데이트 카운트: "+str(item.domeme_update_count)+" 수정일자: "+str(item.modify_date))
        if domeme_info:
            item.set_domeme_price(float(domeme_info['domeme_price']), float(domeme_info['domeme_row_price']))
            # if item.naver_edit_id == -1:
            #     item.naver_edit_id = naver.get_edit_id(item.naver_id)
            #     if item.naver_edit_id == -1:
            #         print("네이버에서 제거됨으로 인한 "+str(item.domeme_id)+" 물건 제거")
            #         item.delete()
            #         continue
            #     else:
            #         print("네이버 에딧 아이디 업데이트: "+str(item.naver_id)+" => "+str(item.naver_edit_id))
            if item.price_state > 0:
                item_dict = vars(item)
                (naver_price, naver_sale) = naver.set_price(item_dict, goto_page=True, depth=1)
                if naver_price and naver_sale:
                    print("변경된 네이버 가격: "+str(naver_price)+" - "+str(naver_sale))
                    item.update_naver_price(naver_price, naver_sale)
                else:
                    print("네이버에서 제거됨으로 인한 "+str(item.domeme_id)+" 물건 제거")
                    item.delete()
                    continue
            item.save()
        else:
            print(str(item.domeme_id)+" 물건 제거")
            item.delete()
        count = count + 1
        end_time = timezone.now()
        delta = end_time - start_time
        average_time = delta.total_seconds() / count
        print("건당 평균 시간: "+format(average_time, ".2f")+"초 전체 시간:"+format(delta.total_seconds(), ".2f")+"초")

    end_time = timezone.now()
    delta = end_time - start_time
    print("총 걸린 시간: "+format(delta.total_seconds(), ".2f")+"초")
    return redirect(reverse('store:index'))

def load_naver_price(request):
    item_list = ItemData.objects.filter(user=request.user).order_by('margin_ratio')
    naver = get_naver(request)

    for item in item_list:
        naver_info = naver.get_item_info(item.naver_id)
        if naver_info:
            item.update_with_naver_info(naver_info)
            item.save()          
    return redirect(reverse('store:index'))

def print_from_dict(item_dict, key):
    if item_dict[key]:
        print(item_dict['scout_category'])
    else:
        print(str(key)+" 아이템이 없어서 출력할 수 없음")

def check_tag(request):
    item_list = ItemData.objects.filter(user=request.user, category_score__gt=0).order_by('-category_score', 'modify_date')
    #item_list = [item_list[0]]
    check_category_item_list(request, item_list, depth=1)
    return redirect(reverse('store:index'))

def depth_print(input_str="", depth=0):
    indent = ""
    for i in range(depth):
        indent += "  "
    print(indent + "[View] " + input_str)

def check_category_item(request, item, depth=0, scout=None, naver=None):
    item_dict = None

    is_delete = False
    while ((not item_dict) or (not 'naver_category' in item_dict) or (item_dict['naver_category'] is None)):
        item_dict = vars(item)
        (naver_result, item_dict) = naver.get_category(item_dict, depth=depth+1, with_save=False)
        if naver_result == True and not item_dict:
            depth_print("네이버에서 삭제된 아이템 삭제", depth=depth+1)
            if item.pk:
                item.delete()
            naver.cancel_item_page(depth=depth+1)
            is_delete = True
            return (False, item_dict)

    (scout_result, item_dict) = scout.get_category(item_dict, depth=depth+1)

    #print_from_dict(item_dict, 'naver_category')
    #print_from_dict(item_dict, 'scout_category')
    
    min_category_info=[99999,'']
    category_index = 1
    category_string_list = []
    for category in item_dict['scout_category']:
        weight = 1000
        score = 0

        # 카테고리 별 점수 책정
        for index in range(min(len(category), len(item_dict['naver_category']))):
            if category[index] != item_dict['naver_category'][index]:
                score = score + weight * category_index
            weight = weight / 10

        # 최적 카테고리 선택 루틴
        if min_category_info[0] > score:
            min_category_info[0] = score
            min_category_info[1] = ">".join(category)
            depth_print("카테고리 분석 최저점 달성 "+str(min_category_info), depth=depth+1)
        else:
            depth_print("최저점 달성 실패 점수: "+str(score)+" 카테고리 스트링: "+(">".join(category)), depth=depth+1)
        category_string_list.append(">".join(category))

    # 대분류 비수정으로 선택가능한 카테고리가 없는 경우
    item_dict['category_current'] = item_dict['naver_category']
    item_dict['category_list'] = category_string_list
    if min_category_info[0] < 9999:
        item_dict['category_score'] = min_category_info[0]
        item_dict['category_recommand'] = min_category_info[1]
    else: # 대분류 비수정으로 선택가능한 카테고리가 있을 경우
        item_dict['category_score'] = 99999
        if len(item_dict['category_list']) > 0:
            item_dict['category_recommand'] = item_dict['category_list'][0]
        else:
            item_dict['category_recommand'] = ""

    if min_category_info[0] > 0:
        if min_category_info[0] < 1000:
            depth_print("소분류 변경 필요", depth=depth+1)
            naver.set_recommand_category(item_dict, depth=depth+1)
            item.set_item_info(item_dict)
        elif min_category_info[0] < 9999:
            depth_print("대분류 변경 필요", depth=depth+1)
            naver.save_item_page(depth=depth+1)
            (result, new_item_dict) = naver.set_main_category(item_dict, depth=depth+1)
            if result == 1:
                new_item_dict['category_score'] = 0
                item.set_item_info(new_item_dict)
            elif result == -1:
                print("권한 제한 아이템 삭제")
                naver.delete_item_with_domeme_id(item_dict, depth=depth+1)
                item.delete()
        else:
            depth_print("카테고리를 획득하지 못한 경우 유저가 검색어를 조정해주어야 함", depth=depth+1)

store/templates/store/itemdata_detail.html
{% extends 'base.html' %}
{% load project_tags %}
{% load static %}

{% block css %}
{% comment %} <link rel="stylesheet" href="tree_fontello/css/fontello.css"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/tree.css' %}">
{% endblock %}

{% block content %}
{% if itemdata %}
<h1>{{ itemdata.title }}</h1>
<div>
    네이버 링크:
    {% if itemdata.naver_edit_id >= 0 %}
    <a href="https://sell.smartstore.naver.com/#/products/edit/{{ itemdata.naver_edit_id }}">
        {{ itemdata.naver_id }}
    </a>
    {% else %}
    {{ itemdata.naver_id }}
    {% endif %}
</div>
<div>
    도매매 링크:
    <a href="http://domeme.domeggook.com/s/{{ itemdata.domeme_id }}">{{ itemdata.domeme_id }}</a>
</div>
<div>
    현재 카테고리 점수: {{ itemdata.category_score }}
</div>
<div>
    현재 카테고리: {{ itemdata.category_current }}
</div>
<div>
    추천 카테고리: {{ itemdata.category_recommand }}
</div>
{% else %}
{{ domemedata }}
{% endif %}
{% endblock %}

store/templates/store/itemdata_list.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block content %}
{% if soldout_list %}
<div>
품절 리스트
<a href="{% url 'store:clear_soldout' %}">품절 물건 제거<a/>
<table class="table table-hover">
  <tr>
    <th scope="col">도매매 번호</th>
    <th scope="col">스토어 번호</th>
    <th scope="col">물건 이름</th>
    <th scope="col">물건 가격</th>
    <th scope="col">물건 상태</th>
  </tr>
{% for soldout in soldout_list %}
  <tr>
    <td><a href="http://domeme.domeggook.com/s/{{ soldout.domeme_id }}">{{ soldout.domeme_id }}</a></td>
    <td><a href="https://sell.smartstore.naver.com/#/products/edit/{{ soldout.naver_edit_id }}">{{ soldout.store_no }}</a></td>
    <td>{{ soldout.name }}</td>
    <td>{{ soldout.price }}</td>
    <td>{{ soldout.domeme_status }}</td>
  </tr>
</table>
{% endfor %}
{% endif %}
<div>
  아이템 리스트 ({{ item_list.count }}개)
  <a href={% url 'store:create_item' %}>+ 새 아이템 추가</a> <a href={% url 'store:delete_duplicate_item' %}>중복 아이템 제거</a>
  <div>
    <a href={% url 'store:refresh_oldest' %}>오래된 아이템부터 전부 갱신</a>
  </div>
  <div>
    <span>
      <a href="{% url 'store:load_naver_data_limit' 200 %}">최신 네이버 아이템 리스트 가져오기(200개 이하)<a></br>
      <a href="{% url 'store:load_naver_data' %}">네이버 아이템 리스트 가져오기<a>
    </span>
    <span>
      <a href="{% url 'store:load_domeme_data' %}">도매매 가격 리스트 가져오기<a>
    </span>
  </div>
  <div>
    <a href="{% url 'store:refresh_no_detail_page' %}">상세 페이지 미 설정 페이지 수 {{ no_detail_page_count }}</a>
  </div>
  <table class="table table-hover">
    <tr>
      <th scope="col">
        네이버 아이디 <a href="{% url 'store:refresh_unset_naver_edit_id' %}">수정 아이디 갱신 ({{ unset_naver_edit_id.count }}건)</a>
      </th>
      <th scope="col">
        도매매 아이디
      </th>
      <th scope="col">
        카테고리 점수 <a href="{% url 'store:index_order_by_category_score' %}">정렬</a></br>
        <a href={% url 'store:check_tag' %}>태그 확인 및 갱신</a>
      </th>
      <th scope="col">
        상품명 <a href="{% url 'store:title_replace_view' %}">상품명 치환</a>
        <form action="{% url 'store:title_replace_with_search' %}" method="POST">
          {% csrf_token %}
          <input type="text" name="search_text">
          <input type="submit" value="치환">
        </form>
      </th>
      <th scope="col">
        도매매 가격
      </th>
      <th scope="col">
        네이버 가격 <a href="{% url 'store:load_naver_price' %}">갱신</a>
      </th>
      <th scope="col">
        네이버 세일가<br>
        <a href="{% url 'store:refresh_unset_naver_sale_price' %}">비지정 대상 갱신({{unset_sale_count}}건)</a>
      </th>
      <th scope="col">
        마진율 <br>
        <a href="{% url 'store:refresh_uncorrect_margin' %}"><10% 갱신</a>
        <a href="{% url 'store:refresh_uncorrect_upper_margin' %}">>25% 갱신({{uncorrect_upper_margin.count}}건)</a>
      </th>
      <th scope="col">
        갱신<br>
        <a href="{% url 'store:refresh_minimum_count_list' %}">최소 수량 변경분</a>
      </th>
    </tr>
  {% for item in item_list %}
    <tr>
      <td>
        {% if item.naver_edit_id >= 0 %}
          <a href="https://sell.smartstore.naver.com/#/products/edit/{{ item.naver_edit_id }}">
            {{ item.naver_id }}
          </a>
        {% else %}
          {{ item.naver_id }}
        {% endif %}
      </td>
      <td>
        <a href="http://domeme.domeggook.com/s/{{item.domeme_id}}">{{ item.domeme_id }}</a>
      </td>
      <td>
        {{ item.category_score }}
      </td>
      <td>
        <a href={% url 'store:detail_item' item.id %}><h5>{{ item.title }}</h5></a>
      </td>
      <td>
        {{ item.domeme_price|mul:item.minimum_count|floatformat:"0" }}원
      </td>
      <td>
        {{ item.naver_price|sub:item.naver_sale|floatformat:"0" }}원({{ item.naver_price|floatformat:"0" }}원)
      </td>
      <td>
        {{ item.naver_sale|floatformat:"0" }}원
      </td>
      <td>
        {{ item.margin_ratio|floatformat:"2" }}%
      </td>
      <td>
        <a href="{% url 'store:refresh_item' item.id %}">수치 갱신</a>
      </td>
    </tr>
  {% endfor %}
  </table>
</div>
{% endblock %}

store/templates/store/soldout_list.html
{% extends 'base.html' %}

{% block content %}
<div>
품절 리스트
{{ soldout_list }}
</div>
<div>
  아이템 리스트
  <a href={% url 'project:create_project' %}>+ 새 아이템 추가</a>
  {% for project in object_list %}
  <a href={% url 'project:detail_project' project.id %}><h5>{{ project }}</h5></a>
  {% endfor %}
</div>
{% endblock %}