mnec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wiki/', include('nec_wiki.urls')),
    url(r'^todo/', include('nec_todo.urls')),
    url(r'^calendar/', include('nec_calendar.urls')),
    url(r'^bank/', include('nec_bank.urls')),
    url(r'', include('nec.urls')),
    path(r'project/', include('project.urls')),
    path(r'store/', include('store.urls')),
]

nec/urls.py
"""Autogen for url."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^accounts/login/', auth_views.LoginView.as_view(), name='login',
        kwargs={'template_name': 'nec/login.html'}),
    url(r'^accounts/logout/', auth_views.LogoutView.as_view(), name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^accounts/signup/', views.signup, name='signup'),
    url(r'^bank/', views.bank, name='bank_index'),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_project/', views.CreateProjectView.as_view(), name='create_project'),
    path('detail_project/<int:pk>/', views.DetailProjectView.as_view(), name='detail_project'),
    path('create_projecttodo/<int:project_id>/<int:todo_id>/', views.create_project_todo, name='create_projecttodo'),
    path('delete_projecttodo/<int:todo_id>/', views.delete_project_todo, name='delete_projecttodo'),
    path('edit_projecttodo/<int:pk>/', views.EditProjectTodoView.as_view(), name='edit_projecttodo'),
    path('clear_projecttodo/<int:todo_id>/', views.clear_project_todo, name='clear_projecttodo'),
    path('add_priority_projecttodo/<int:todo_id>/<value>/', views.add_priority_projecttodo, name='add_priority_projecttodo'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('order_by/category_score', views.index_order_by_category_score, name='index_order_by_category_score'),
    path('detail/<int:pk>/', views.ItemDataDetailView.as_view(), name='detail_item'),
    path('clear_soldout/', views.clear_soldout, name='clear_soldout'),
    path('load_naver_data/', views.load_naver_data, name='load_naver_data'),
    path('load_naver_data/<int:load_count>/', views.load_naver_data, name='load_naver_data_limit'),
    path('load_domeme_data/', views.load_domeme_data, name='load_domeme_data'),
    path('load_naver_price/', views.load_naver_price, name='load_naver_price'),
    path('create_item/', views.create_item, name='create_item'),
    path('refresh_item/<int:pk>/', views.refresh_item_view, name='refresh_item'),
    path('refresh_uncorrect_margin/', views.refresh_uncorrect_margin, name='refresh_uncorrect_margin'),
    path('refresh_unset_naver_sale_price/', views.refresh_unset_naver_sale_price, name='refresh_unset_naver_sale_price'),
    path('refresh_uncorrect_upper_margin/', views.refresh_uncorrect_upper_margin, name='refresh_uncorrect_upper_margin'),
    path('title_replace_view/', views.title_replace_view, name='title_replace_view'),
    path('refresh_minimum_count_list/', views.refresh_minimum_count_list, name='refresh_minimum_count_list'),
    path('delete_duplicate_item/', views.delete_duplicate_item, name='delete_duplicate_item'),
    path('refresh_oldest/', views.refresh_oldest, name='refresh_oldest'),
    path('refresh_unset_naver_edit_id/', views.refresh_unset_naver_edit_id, name='refresh_unset_naver_edit_id'),
    path('title_replace_with_search/', views.title_replace_with_search, name='title_replace_with_search'),
    path('check_tag/', views.check_tag, name='check_tag'),
    path('reset_category_score/', views.reset_category_score, name='reset_category_score'),
    path('refresh_no_detail_page/', views.refresh_no_detail_page, name='refresh_no_detail_page'),
]

nec/models.py
"""Get db models."""
from django.db import models
from django.utils import timezone


# Create your models here.
class BucketList(models.Model):
    """Start with BucketList. but now we do not use it."""

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    text = models.TextField(null=True)
    created_date = models.DateTimeField()
    deadline_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        """Bucketlist to string.

        [ <author> ] title.
        """
        return "[" + str(self.author) + "]" + self.title


class MoneyUnit(models.Model):
    """For my account book."""

    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    category = models.CharField(max_length=1024)
    title = models.CharField(max_length=1024)
    text = models.TextField(null=True)
    balance = models.IntegerField()
    created_date = models.DateTimeField(blank=False, null=False)

    def __str__(self):
        """Moneyunit to string.

        [ <author> ][ <category> ] title.
        """
        return "[" + str(self.author) + "][" + self.category + "]" + self.title

nec_wiki/forms.py
from django.forms import ModelForm, widgets
from .models import Page, Tag
from django import forms


class PageForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    tags = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        super(PageForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.initial['title'] = self.instance.title
            self.initial['content'] = self.instance.content
            self.initial['tags'] = self.instance.getTags()

class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

nec/views.py
"""Django shortcuts."""
from django.shortcuts import render, redirect
import datetime
from django.conf import settings
from .models import MoneyUnit, BucketList
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.urls import reverse, reverse_lazy
from nec_todo.models import Todo
from django.views.generic.edit import CreateView


def dashboard(request):
    if request.user.is_authenticated:
        return redirect(reverse('todo_index'))
    # if request.user.is_authenticated:
    #     bucketlists = BucketList.objects.filter(
    #         author=request.user,
    #         created_date__lte=datetime.datetime.now()).order_by('-created_date')
    #     todolists = Todo.objects.filter(
    #         owner=request.user,
    #         created_date__lte=datetime.datetime.now()).order_by('-created_date')
    #     return render(request, 'nec/dashboard.html',
    #                   {'bucketlists': bucketlists, 'todolists': todolists})
    else:
        return redirect(settings.LOGIN_URL)


def bank(request):
    if request.user.is_authenticated:
        money_unit_lists = MoneyUnit.objects.filter(
            created_date__lte=datetime.datetime.now()).order_by('-created_date')
        return render(request, 'nec/bank.html',
                      {'money_unit_lists': money_unit_lists})
    else:
        return redirect(settings.LOGIN_URL)


class SignupView(CreateView):
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('index')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse("dashboard"))
    else:
        form = UserCreationForm()
    return render(request, 'nec/signup.html', {'form': form})

nec/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>기록{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}

    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    {% block javascript %}{% endblock %}

    <script>
      $(document).ready(() => {
        $('.materialize-chips').chips({% block chips_init %}{% endblock %});
        $("form").on("submit", function() {
          $chips = "";
          $.each($(".materialize-chips").chips('getData'), function(index, chip) {
            $chips += " #" +chip.tag;
          });
          $("#id_tags").attr('value', $chips);
        });
        $(".calendar_today").focus();
      });
    </script>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-danger">
    <a class="navbar-brand" href="{% url 'dashboard' %}">기록</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item text-nowrap"><a class="nav-link" href="{% url 'dashboard' %}">대쉬보드</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item text-nowrap"><a class="nav-link" href="{% url 'logout' %}">로그아웃</a></li>
        {% else %}
        <li class="nav-item text-nowrap"><a class="nav-link" href="{% url 'login' %}">로그인</a></li>
        {% endif %}
    </ul>
      {% comment %} <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div> {% endcomment %}
  </nav>

<!-- Page Layout -->

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link {% block todo_active %}{% endblock %}" href="{% url 'todo_index' %}"><li class="collection-header ">할 일</a>
              {% block todo_inner %}{% endblock %}
            </li>
            <li class="collection-header ">
              <a class="nav-link {% block bank_active %}{% endblock %}" href="{% url 'bank_index' %}">가계부</a>
              {% block bank_inner %}{% endblock %}
            </li>
            <li class="collection-header">
              <a class="nav-link {% block wiki_active %}{% endblock %}" href="{% url 'wiki_index' %}">위키</a>
              {% block wiki_inner %}{% endblock %}
            </li>
            <li class="collection-header ">
              <a class="nav-link {% block project_active %}{% endblock %}" href="{% url 'project:index' %}">프로젝트</a>
              {% block project_inner %}{% endblock %}
            </li>
            <li class="collection-header ">
              <a class="nav-link {% block store_active %}{% endblock %}" href="{% url 'store:index' %}">오토스토어 관리</a>
              {% block store_inner %}{% endblock %}
            </li>
          </ul>
        </div>
      </nav>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        {% block content %}
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        {% endblock %}
        </div>
      </main>
    </div>
  </div>
</div>

    <div>
    <h1>임시 푸터 몰아내기</h1>
    </div>
    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

  <!-- Footer -->
  <footer class="page-footer font-small bg-danger fixed-bottom">

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2018 Copyright:
        <a href="igam0000@gmail.com">hanchi</a>, All rights reserved.
      </div>
      <!-- Copyright -->
  </footer>
</html>
<!-- Footer -->

nec/templates/base_material_lite.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>기록{% block title %}{% endblock %}</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css" />
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
    {% block css %}{% endblock %}
    {% block javascript %}{% endblock %}
  </head>
  <body>
    <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">기록</span>
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search">
              <label class="mdl-textfield__label" for="search">Enter your query...</label>
            </div>
          </div>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
          {% if user.is_authenticated %}
            <a href="{% url 'login' %}"><li class="mdl-menu__item">로그아웃</li></a>
          {% else %}
            <a href="{% url 'logout' %}"><li class="mdl-menu__item">로그인</li></a>
          {% endif %}
          </ul>
        </div>
      </header>
      <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
        <header class="demo-drawer-header">
          <img src="images/user.jpg" class="demo-avatar">
          <div class="demo-avatar-dropdown">
            <span>{{ request.user.username }}</span>
            <!-- <div class="mdl-layout-spacer"></div>
            <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
              <i class="material-icons" role="presentation">arrow_drop_down</i>
              <span class="visuallyhidden">Accounts</span>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
              <li class="mdl-menu__item">hello@example.com</li>
              <li class="mdl-menu__item">info@example.com</li>
              <li class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</li>
            </ul> -->
          </div>
        </header>
        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
          <a class="mdl-navigation__link" href="{% url 'todo_index' %}"><i class="mdl-color-text--blue-grey-400 material-icons {% block todo_active %}{% endblock %}" role="presentation">할일</i></a>
          {% block todo_inner %}{% endblock %}
          <a class="mdl-navigation__link" href="{% url 'bank_index' %}"><i class="mdl-color-text--blue-grey-400 material-icons {% block bank_active %}{% endblock %}" role="presentation">가계부</i></a>
          {% block bank_inner %}{% endblock %}
          <a class="mdl-navigation__link" href="{% url 'wiki_index' %}"><i class="mdl-color-text--blue-grey-400 material-icons {% block wiki_active %}{% endblock %}" role="presentation">위키</i></a>
          <div class="mdl-layout-spacer"></div>
          {% block wiki_inner %}{% endblock %}
        </nav>
      </div>
      <main class="mdl-layout__content mdl-color--grey-100">
        <div class="mdl-grid demo-content">
          <div class="demo-charts mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </main>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>