mnec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wiki/', include('nec_wiki.urls')),
    url(r'^todo/', include('nec_todo.urls')),
    url(r'^calendar/', include('nec_calendar.urls')),
    url(r'^bank/', include('nec_bank.urls')),
    url(r'', include('nec.urls')),
    path(r'project/', include('project.urls')),
    path(r'store/', include('store.urls')),
]

nec/urls.py
"""Autogen for url."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^accounts/login/', auth_views.LoginView.as_view(), name='login',
        kwargs={'template_name': 'nec/login.html'}),
    url(r'^accounts/logout/', auth_views.LogoutView.as_view(), name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^accounts/signup/', views.signup, name='signup'),
    url(r'^bank/', views.bank, name='bank_index'),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_project/', views.CreateProjectView.as_view(), name='create_project'),
    path('detail_project/<int:pk>/', views.DetailProjectView.as_view(), name='detail_project'),
    path('create_projecttodo/<int:project_id>/<int:todo_id>/', views.create_project_todo, name='create_projecttodo'),
    path('delete_projecttodo/<int:todo_id>/', views.delete_project_todo, name='delete_projecttodo'),
    path('edit_projecttodo/<int:pk>/', views.EditProjectTodoView.as_view(), name='edit_projecttodo'),
    path('clear_projecttodo/<int:todo_id>/', views.clear_project_todo, name='clear_projecttodo'),
    path('add_priority_projecttodo/<int:todo_id>/<value>/', views.add_priority_projecttodo, name='add_priority_projecttodo'),
]

project/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

# Create your models here.
class Project(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    update_date = models.DateTimeField(blank=True, null=True)
    todo = models.ForeignKey('ProjectTodo', null=True, default=None, on_delete=models.CASCADE, related_name='todo_list')

    def __str__(self):
        return self.title

class ProjectTodo(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255)
    detail = models.TextField(null=True, blank=True, default="")
    depth = models.IntegerField(default=0, null=False, blank=False)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='child', on_delete=models.SET_NULL)
    is_clear = models.BooleanField(default=False)
    clear_date = models.DateTimeField(default=None, null=True)
    priority = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id) + " " + self.title + " (" + str(self.depth) + ")"

project/forms.py
from django import forms
from .models import ProjectTodo

class ProjectTodoForm(forms.ModelForm):
    class Meta:
        model = ProjectTodo
        fields = ['title', 'detail']

project/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.utils import timezone

from .models import Project, ProjectTodo
from .forms import ProjectTodoForm

# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 50

class CreateProjectView(LoginRequiredMixin, generic.CreateView):
    model = Project
    fields = ['title']
    success_url = reverse_lazy('project:index')

    def form_valid(self, form):
        project = form.save(commit=False)
        project.author = self.request.user
        result = super(CreateProjectView, self).form_valid(form)

        project_todo = ProjectTodo.objects.create(author=self.request.user, project=project, title=project.title, depth=0)
        project_todo.save()

        project.todo = project_todo
        project.save()

        return result


class DetailProjectView(LoginRequiredMixin, generic.DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(DetailProjectView, self).get_context_data(**kwargs)
        context['child'] = ProjectTodo.objects.filter(project=self.get_object())
        context['child_clear_log'] = ProjectTodo.objects.filter(project=self.get_object(), is_clear=True).order_by('-clear_date')
        context['total_child_count'] = ProjectTodo.objects.filter(project=self.get_object()).count()
        context['total_clear_count'] = ProjectTodo.objects.filter(project=self.get_object(), is_clear=True).count()
        return context

def create_project_todo(request, project_id, todo_id=None):
    if request.method == 'POST':
        form = ProjectTodoForm(request.POST, request.FILES)

        if form.is_valid():
            project_todo = form.save(commit=False)
            project_todo.author = request.user
            project = Project.objects.get(pk=project_id)
            project_todo.project = project
            if todo_id:
                todo = ProjectTodo.objects.get(pk=todo_id)
                project_todo.parent = todo
                project_todo.depth = todo.depth + 1
            project_todo.save()
            return HttpResponseRedirect(reverse('project:detail_project', args=[project_id]))
    else:
        form = ProjectTodoForm()
        return render(request, 'project/create_todo.html', {
            'form': form,
        })

def delete_reverse_cascade(todo):
    todo = ProjectTodo.objects.filter(parent=todo)
    for t in todo:
        delete_reverse_cascade(t)
        t.delete()

def delete_project_todo(request, todo_id):
    todo = ProjectTodo.objects.get(id=todo_id)
    project_id = todo.project.id
    delete_reverse_cascade(todo)
    todo.delete()
    return HttpResponseRedirect(reverse('project:detail_project', args=[project_id]))

class EditProjectTodoView(LoginRequiredMixin, generic.edit.UpdateView):
    model = ProjectTodo
    fields = ['title', 'detail']

    def get_success_url(self):
        return reverse('project:detail_project', args=[self.object.project.id])

def clear_project_todo(request, todo_id):
    todo = ProjectTodo.objects.get(id=todo_id)
    if todo.is_clear:
        todo.is_clear = False
        todo.clear_date = None
    else:
        todo.is_clear = True
        todo.clear_date = timezone.now()
    todo.save()
    return HttpResponseRedirect(reverse('project:detail_project', args=[todo.project.id]))

def add_priority_projecttodo(request, todo_id, value):
    todo = ProjectTodo.objects.get(id=todo_id)
    todo.priority = todo.priority + int(value)
    todo.save()
    return HttpResponseRedirect(reverse('project:detail_project', args=[todo.project.id]))

project/templates/project/child.html
{% load project_tags %}

<ul class="tree">
{% for child in childs %}
    <li>
        {% if child.child.count > 0 %}
        <input type="checkbox" checked="checked" id="todo_{{ child.id }}" />
        {% endif %}
        <a href="{% url 'project:add_priority_projecttodo' child.id 1 %}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
            </svg>
        </a>
        <a href="{% url 'project:add_priority_projecttodo' child.id -1 %}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
            </svg>
        </a>
        {% if child.is_clear %}
        <strike style="color:gray">
        {% endif %}
        {% if child.child.count > 0 %}
        <label class="tree_label" for="todo_{{ child.id }}">{{ child.title }}</label>
        {% else %}
        <span class="tree_label">{{ child.title }}</span>
        {% endif %}
        <a href="{% url 'project:clear_projecttodo' child.id %}">
        {% if child.is_clear %}
        [O]
        {% else %}
        [X]
        {% endif %}
        </a>
        <a href="{% url 'project:edit_projecttodo' child.id %}">E</a>
        <a href="{% url 'project:create_projecttodo' child.project.id child.id %}">+</a>
        <a href="{% url 'project:delete_projecttodo' child.id %}">X</a>
        {% if child.is_clear %}
        </strike>
        {% endif %}
        {% if child.detail|length > 0 and not child.is_clear %}
        </br><h6>{{ child.detail | safe }}</h6>
        {% endif %}
        {% if child.child.count > 0 %}
        {% show_childs child %}
        {% endif %}
    </li>
{% endfor %}
</ul>

project/templates/project/create_todo.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="추가">
</form>
{% endblock %}

project/templates/project/project_detail.html
{% extends 'base.html' %}
{% load project_tags %}
{% load static %}

{% block css %}
{% comment %} <link rel="stylesheet" href="tree_fontello/css/fontello.css"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/tree.css' %}">
{% endblock %}

{% block content %}
{% if object.todo %}
<h2>프로젝트 트리 {{ total_clear_count }}/{{ total_child_count }}</h2>
<ul class="tree">
    <li>
        <input type="checkbox" checked="checked" id="todo_{{ object.todo.id }}" />
        {% if object.todo.child.count > 0 %}
        <label class="tree_label" for="todo_{{ object.todo.id }}">{{ object.todo.title }}</label>
        {% else %}
        <span class="tree_label">{{ object.todo.title }}</label> 
        {% endif %}
        <a href="{% url 'project:create_projecttodo' object.id object.todo.id %}">+</a>
        {% show_childs object.todo %}
    </li>
</ul> 
{% endif %}

<h2>클리어 로그</h2>
{% for c in child_clear_log %}
<div>
{{ c.clear_date|date }} - {{ c.title }} 완료
</div>
{% endfor %}
{% endblock %}

project/templates/project/project_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="추가">
</form>
{% endblock %}

project/templates/project/project_list.html
{% extends 'base.html' %}

{% block content %}
<div>
  PROJECT list
  <a href={% url 'project:create_project' %}>+ 새 프로젝트 추가</a>
  {% for project in object_list %}
  <a href={% url 'project:detail_project' project.id %}><h5>{{ project }}</h5></a>
  {% endfor %}
  </div>
{% endblock %}

project/templates/project/projecttodo_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="추가">
</form>
{% endblock %}