mnec/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wiki/', include('nec_wiki.urls')),
    url(r'^todo/', include('nec_todo.urls')),
    url(r'^calendar/', include('nec_calendar.urls')),
    url(r'^bank/', include('nec_bank.urls')),
    url(r'', include('nec.urls')),
    path(r'project/', include('project.urls')),
    path(r'store/', include('store.urls')),
]

nec/urls.py
"""Autogen for url."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^accounts/login/', auth_views.LoginView.as_view(), name='login',
        kwargs={'template_name': 'nec/login.html'}),
    url(r'^accounts/logout/', auth_views.LogoutView.as_view(), name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^accounts/signup/', views.signup, name='signup'),
    url(r'^bank/', views.bank, name='bank_index'),
]

nec_todo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='todo_index'),
    url(r'^list$', views.list_all, name='todo_list'),
    url(r'^create/$', views.create, name='todo_create'),
    url(r'^create_simple/$', views.create_simple, name='todo_create_simple'),
    url(r'^view/(?P<todo_name>.+)/$', views.view, name='todo_view'),
    url(r'^edit/(?P<todo_id>[^/]+)/$', views.edit, name='todo_edit'),
    url(r'^delete/(?P<todo_id>[^/]+)/$', views.delete, name='todo_delete'),
    url(r'^do/(?P<todo_id>[^/]+)/(?P<update>[^/]+)/$', views.do, name='todo_do'),
    url(r'^undo/(?P<todo_id>[^/]+)/$', views.undo, name='todo_undo'),
    url(r'^delay_enddate/(?P<todo_id>[^/]+)/(?P<day>[^/]+)$', views.delay_enddate, name='todo_delay_enddate'),
]

nec_todo/models.py
import markdown
import re
from django.db import models
from django.urls import reverse


# Create your models here.
class Todo(models.Model):
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    content = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    daily = models.BooleanField()
    daily_page = models.TextField(blank=True)
    complete = models.BooleanField()

    def __str__(self):
        if self.end_date is self.created_date:
            return "[%s ~ %s] %s" % (str(self.created_date),
                                     str(self.end_date),
                                     self.title)
        else:
            return "[%s ~ ] %s" % (str(self.created_date),
                                   self.title)

    def get_absolute_url(self):
        return reverse('todo_view', args=(self.title, ))

    def get_event_tuple(self):
        return [self.start_date]

    def get_markdown_content(self):
        return markdown.markdown(re.sub(r"\n", "<br />", self.content))

nec_todo/forms.py
from django.forms import ModelForm, widgets, Textarea, TextInput
from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'content', 'start_date', 'end_date', 'daily', 'daily_page']

nec_todo/views.py
"""using url in function."""
from django.db.models import F, Q
from django.urls import reverse
from .models import Todo
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from .forms import TodoForm
from django.contrib.auth.decorators import login_required
from nec_calendar.classes.calendar import Calendar
from django.utils import timezone
from nec_wiki.models import Page
from django.db.models import Q
from datetime import timedelta,date
from django.utils.text import Truncator


# Create your views here.
# def index(request):
#     """Todo index page.
#
#     list up all todo with current user
#     """
#     return calendar(request, timezone.datetime.now().year, timezone.datetime.now().month)

# Create your views here.
@login_required(login_url=settings.LOGIN_URL)
def index(request):
    todo_list = get_event_array(request, False)
    return render(request, 'nec_todo/calendar.html', {'todo_list':todo_list})


@login_required(login_url=settings.LOGIN_URL)
def list_all(request):
    tommorow = date.today() + timedelta(1)
    daily_list = Todo.objects.filter(owner=request.user, complete=False, daily=True, end_date__lt=tommorow).order_by('end_date')
    todo_list = Todo.objects.filter(owner=request.user, complete=False, daily=False).order_by('end_date')
    return render(request, 'nec_todo/todo_list.html', {'todo_list':todo_list, 'daily_list':daily_list})

@login_required(login_url=settings.LOGIN_URL)
def get_event_array(request, daily):
    if daily is True:
        todo_list = Todo.objects.filter(owner=request.user)
    else:
        todo_list = Todo.objects.filter(owner=request.user, daily=False)

    todo_array = []

    for todo in todo_list:
        todo_array.append(todo.get_event())

    return ",".join(todo_array)

def recent_list(request):
    """Todo recent list page.

    list up all todo with current user
    """
    todo_filter = Todo.objects.filter(owner=request.user,
                                      created_date__lte=timezone.datetime.now())
    todo_list = todo_filter.order_by('-created_date')
    return render(request, 'nec_todo/recent_list.html',
                  {'todo_list': todo_list, 'user_name': request.user.username})


@login_required(login_url=settings.LOGIN_URL)
def create(request):
    """Create todo object."""
    if request.method == 'POST':
        form = TodoForm(request.POST, request.FILES)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.owner = request.user
            todo.complete = False
            todo.save()
            return redirect(todo)
        else:
            return render(request, 'nec_todo/create.html', {'todo_form': form})
    else:
        form = TodoForm(request.GET)
        return render(request, 'nec_todo/create.html', {'todo_form': form})

@login_required(login_url=settings.LOGIN_URL)
def create_simple(request):
    """Create todo object."""
    if request.method == 'POST':
        form = TodoForm(request.POST, request.FILES)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.owner = request.user
            todo.complete = False
            todo.save()
            return redirect(todo)
        else:
            return render(request, 'nec_todo/create_simple.html', {'todo_form': form, 'error_msg': error_msg})
    else:
        return render(request, 'nec_todo/create_simple.html')

@login_required(login_url=settings.LOGIN_URL)
def view(request, todo_name):
    """View todo objects.

    Search todo objects with request.user, todo_name
    todo can generate same title
    """
    todo_list = Todo.objects.filter(owner=request.user, title=todo_name)
    return render(request, 'nec_todo/view.html',
                  {'todo_list': todo_list})

@login_required(login_url=settings.LOGIN_URL)
def delay_enddate(request, todo_id, day):
    """Edit todo content.

    when edit todo, search with todo_id.
    todo_name is not unique.
    """
    todo = get_object_or_404(Todo, id=todo_id)
    todo.end_date = todo.end_date + timedelta(days=int(day))
    todo.save()
    return redirect(request.META['HTTP_REFERER'])

@login_required(login_url=settings.LOGIN_URL)
def edit(request, todo_id):
    """Edit todo content.

    when edit todo, search with todo_id.
    todo_name is not unique.
    """
    todo = get_object_or_404(Todo, id=todo_id)
    if request.method == 'POST':
        form = TodoForm(request.POST, request.FILES, instance=todo)
        if form.is_valid():
            todo = form.save()
            return redirect(todo)
        else:
            return render(request, 'nec_todo/edit.html',
                          {'todo': todo, 'todo_form': form})

    else:
        form = TodoForm(instance=todo)
        return render(request, 'nec_todo/edit.html',
                      {'todo': todo, 'todo_form': form})


@login_required(login_url=settings.LOGIN_URL)
def delete(request, todo_id):
    """Delete todo object."""
    todo = Todo.objects.get(id=int(todo_id), owner=request.user)
    title = todo.title
    todo.delete()
    if "view/" in request.META['HTTP_REFERER']:
        return redirect(reverse('todo_index'))
    else:
        return redirect(request.META['HTTP_REFERER'])


@login_required(login_url=settings.LOGIN_URL)
def do(request, todo_id, update):
    """Do todo object.

    if todo.daily is True. todo obect is copy & save with current time
    and then write 'do todo object' in wiki_page.
    else just complete todo object.
    """
    todo = Todo.objects.get(id=int(todo_id), owner=request.user)
    now = timezone.now()
    if update == 1:
        if todo.daily:
            now = timezone.now()
            new_todo = Todo(owner=todo.owner, title=todo.title, content=todo.content,
                            start_date=now.astimezone().strftime('%Y-%m-%d'),
                            end_date=now.astimezone().strftime('%Y-%m-%d %H:%M:%S'),
                            daily=False, daily_page=todo.daily_page, complete=True)
            new_todo.save()
            next_day = now + timezone.timedelta(days=1)
            todo.start_date = next_day.astimezone().strftime('%Y-%m-%d')
            todo.end_date = next_day.astimezone().strftime('%Y-%m-%d')
            todo.save()
        else:
            todo.complete = True
            todo.end_date = timezone.datetime.now()
            todo.save()
    else:
        todo.complete = True
        todo.save()


    if todo.daily_page:
        try:
            page = Page.objects.get(owner=request.user, title=todo.daily_page)
        except Page.DoesNotExist:
            page = Page(owner=request.user, title=todo.daily_page)
        log_msg = "%s <a href=\"%s\">%s</a>을 완료함.</br>" % (now.astimezone().strftime('%Y-%m-%d %H:%M:%S'),
                                                              reverse('todo_view', args=(todo.title,)),
                                                              todo.title)
        page.todo_log = log_msg + page.todo_log
        page.save()
    return redirect(request.META['HTTP_REFERER'])

@login_required(login_url=settings.LOGIN_URL)
def undo(request, todo_id):
    """Undo todo object.

    if todo.daily is True. todo obect is copy & save with current time
    and then write 'do todo object' in wiki_page.
    else just complete todo object.
    """
    todo = Todo.objects.get(id=int(todo_id), owner=request.user)
    now = timezone.now()
    todo.complete = False
    todo.save()

    if todo.daily_page:
        try:
            page = Page.objects.get(owner=request.user, title=todo.daily_page)
        except Page.DoesNotExist:
            page = Page(owner=request.user, title=todo.daily_page)
        log_msg = "%s <a href=\"%s\">%s</a>을 재수행함.</br>" % (now.astimezone().strftime('%Y-%m-%d %H:%M:%S'),
                                                                reverse('todo_view', args=(todo.title,)),
                                                                todo.title)
        page.todo_log = log_msg + page.todo_log
        page.save()
    return redirect(reverse('todo_index'))

nec_todo/templates/nec_todo/base.html
{% extends 'base.html' %}

{%  block todo_active %}green lighten-5{% endblock %}

{% block todo_inner %}
<ul>
    <li class="collection-item">목록</li>
    <li class="collection-item">달력</li>
</ul>
{% endblock %}

nec_todo/templates/nec_todo/calendar.html
{% extends 'nec_todo/base.html' %}

{% block content %}
  {% include 'nec_todo/calendar_inner.html' %}
{% endblock %}

nec_todo/templates/nec_todo/calendar_inner.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/nec_calendar/calendar.css' %}">
<link href="{% static 'fullcalendar/core/main.css' %}" rel="stylesheet" />
<link href="{% static 'fullcalendar/daygrid/main.css' %}" rel="stylesheet" />

<script src="{% static 'fullcalendar/core/main.js' %}"></script>
<script src="{% static 'fullcalendar/google-calendar/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.js' %}"></script>
<script type='text/javascript' src="{% static 'fullcalendar/google-calendar/gcal.js' %}"></script>

<script>
  function zeroPad(n, width) {
    n = n + '';
    return n.length >= width ? n : new Array(width - n.length + 1).join('0') + n;
  }

  function getDateString(date) {
    return date.getFullYear() + "-" + zeroPad(date.getMonth() + 1, 2) + "-" + zeroPad(date.getDate(), 2) + " 00:00:00";
  }

  Date.prototype.addDays = function(days) {
      var date = new Date(this.valueOf());
      date.setDate(date.getDate() + days);
      return date;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: ['dayGrid', 'googleCalendar'],
      navLinks: true,
      dayClick: function(date, jsEvent) {
        window.location.replace('create/?start_date='+getDateString(date)+'&end_date='+getDateString(date.addDays(1)));
      },
      navLinkDayClick: function(date, jsEvent) {
        window.location.replace('create/?start_date='+getDateString(date)+'&end_date='+getDateString(date.addDays(1)));
      },
      googleCalendarApiKey: 'AIzaSyB3VSuQOHp1VRz-JA2RYMEz5S8Cp5lpAkc',
      events: [
                {{ todo_list | safe }}{% if todo_list %},{% endif %}
              ],
      eventSources: [
        {
          googleCalendarId: 'igam0000@gmail.com',
          className: 'google event'
        },
      ],
      timeZone: 'Asia/Seoul',
      eventClick: function(info) {
        window.location.replace(info.url);
      },
      height: 'auto',
    });
    calendar.render();
  });
</script>

<div id="calendar"></div>

nec_todo/templates/nec_todo/create.html
{% extends 'nec_todo/base.html' %}

{% block content %}
    <form method="post" action="{% url 'todo_create' %}">
        {% csrf_token %}
        {% include 'includes/model_form.html' with form=todo_form %}
        <button type="submit" class="btn btn-primary">페이지 저장</button>
    </form>
{% endblock %}

{% block javascript %}
    <script>
    $('#id_content').val('New Text');
    $('#id_content').trigger('autoresize');
    </script>
{% endblock %}

nec_todo/templates/nec_todo/create_simple.html
{% extends 'nec_todo/base.html' %}

{% block content %}
{% for field in form.fields %}
{% if field.errors %}
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
{% endif %}
{% endfor %}
  <form method="post" action="{% url 'todo_create_simple' %}">
    {% csrf_token %}
    <div class="row">
      <div class="input-field col s12">
        <label for="id_title">Title:</label>
        <input type="text" name="title" maxlength="1024" required id="id_title" />
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <label for="id_title">반복 요일</label>
        <input type="checkbox" name="day" value="0" /><span>일</span>
        <input type="checkbox" name="day" value="1" /><span>월</span>
        <input type="checkbox" name="day" value="2" /><span>화</span>
        <input type="checkbox" name="day" value="3" /><span>수</span>
        <input type="checkbox" name="day" value="4" /><span>목</span>
        <input type="checkbox" name="day" value="5" /><span>금</span>
        <input type="checkbox" name="day" value="6" /><span>토</span>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <label for="id_daily_page">Daily page:</label>
        <textarea name="daily_page" cols="40" rows="10" id="id_daily_page" class="materialize-textarea"></textarea>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">페이지 저장</button>
  </form>
{% endblock %}

{% block javascript %}
    <script>
    $('#id_content').val('New Text');
    $('#id_content').trigger('autoresize');
    </script>
{% endblock %}

nec_todo/templates/nec_todo/edit.html
{% extends 'nec_todo/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <form method="post" action="{% url 'todo_edit' todo.id %}" novalidate>
        {% csrf_token %}
        {% include 'includes/model_form.html' with form=todo_form %}
        <button type="submit" class="btn btn-primary">페이지 저장</button>
    </form>
{% endblock %}

nec_todo/templates/nec_todo/index.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/nec_calendar/calendar.css' %}">
<link href="{% static 'fullcalendar/core/main.css' %}" rel="stylesheet" />
<link href="{% static 'fullcalendar/daygrid/main.css' %}" rel="stylesheet" />

<script src="{% static 'fullcalendar/core/main.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.js' %}"></script>

<script>
  function zeroPad(n, width) {
    n = n + '';
    return n.length >= width ? n : new Array(width - n.length + 1).join('0') + n;
  }

  function getDateString(date) {
    alert(date);
    return date.getFullYear() + "-" + zeroPad(date.getMonth() + 1, 2) + "-" + zeroPad(date.getDate(), 2) + " 00:00:00";
  }

  Date.prototype.addDays = function(days) {
      var date = new Date(this.valueOf());
      date.setDate(date.getDate() + days);
      return date;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: ['dayGrid'],
      navLinks: true,
      navLinkDayClick: function(date, jsEvent) {
        alert('create/?start_date='+getDateString(date)+'&end_date='+getDateString(date.addDays(1)));
        window.location.replace('create/?start_date='+getDateString(date)+'&end_date='+getDateString(date.addDays(1)));
      },
      events: {{ todo_list | safe }},
      timeZone: 'UTC',
      eventClick: function(info) {
        window.location.replace(info.url);
      },
      height: 'auto',
    });
    calendar.render();
  });
</script>

<div id="calendar"></div>

nec_todo/templates/nec_todo/recent_list.html
{% extends 'nec_todo/base.html' %}

{% block content %}
  {% include 'nec_calendar/calendar' }
  <h1>최근 할 일들</h1></br>
    <a href="{% url 'todo_create' %}"><button class="btn btn-primary">새 할 일 만들기</button></a></br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>할 일</th>
          <th>시작일</th>
          <th>기한일</th>
          <th>수행</th>
        </tr>
      </thead>
      <tbody>
        {% for todo in todo_list %}
        <tr>
          <td>
            <a href="{% url 'todo_view' request.user.username todo.title %}">{{ todo.title }}</a></br>
          </td>
          <td>{{ todo.start_date }}</td>
          <td>{{ todo.end_date }}</td>
          <td>{% if todo.daily %}<code class="highlight">daily</code>{% endif %}<a href="{% url 'todo_do' request.user.username todo.id %}"<button class="btn btn-primary btn-sm {% if todo.complete %}disabled{% endif %}">완료</button></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

nec_todo/templates/nec_todo/todo_list.html
{% extends 'nec_todo/base.html' %}

{% block content %}
  <h3>매일 할 일</h3>
  <a href="{% url 'todo_create_simple' %}"><button class="btn btn-info">할일 추가</button></a>
  <table width="inherit">
  {% for daily in daily_list %}
    <tr>
      <td width=120px>
      {% if daily.is_past_due %}
        <span class="badge badge-primary">{{daily.end_date|timesince}} 지남</span>
      {% else %}
        <span class="badge badge-info">{{daily.end_date|timeuntil}} 남음</span>
      {% endif %}
      </td>
      <td width="inherit" style="word-break:break-all">
      <a href="{% url 'todo_view' daily.title %}">{{ daily.title | truncatechars:30 }}</a>
      </td>
      <td width=200px>
      <a href="{% url 'todo_delay_enddate' daily.id 1 %}"><button class="badge badge-secondary">+1</button></a>
      <a href="{% url 'todo_delay_enddate' daily.id 7 %}"><button class="badge badge-secondary">+7</button></a>
      <a href="{% url 'todo_edit' daily.id %}"><button class="badge badge-info">수정</button></a>
      <a href="{% url 'todo_do' daily.id %}"><button class="badge badge-success">완료</button></a>
      <a href="{% url 'todo_delete' daily.id %}"><button class="badge badge-primary">삭제</button></a>
      </td>
    </tr>
  {% endfor %}
  </table>
  <h3>할 일 목록</h3>
  <table width=100%>
  {% for todo in todo_list %}
    <tr>
      <td>
      {% if todo.is_past_due %}
        <span class="badge badge-primary">{{todo.end_date|timesince}} 지남</span>
      {% else %}
        <span class="badge badge-info">{{todo.end_date|timeuntil}} 남음</span>
      {% endif %}
      </td>
      <td>
      <a href="{% url 'todo_view' todo.title %}">{{ todo.title | truncatechars:30 }}</a>
      </td>
      <td>
      <a href="{% url 'todo_delay_enddate' todo.id 1 %}"><button class="badge badge-secondary">+1</button></a>
      <a href="{% url 'todo_delay_enddate' todo.id 7 %}"><button class="badge badge-secondary">+7</button></a>
      <a href="{% url 'todo_edit' todo.id %}"><button class="badge badge-info">수정</button></a>
      <a href="{% url 'todo_do' todo.id %}"><button class="badge badge-success">완료</button></a>
      <a href="{% url 'todo_delete' todo.id %}"><button class="badge badge-primary">삭제</button></a>
      </td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

nec_todo/templates/nec_todo/view.html
{% extends 'nec_todo/base.html' %}
{% load wikilink %}

{% block content %}
    {% for todo in todo_list %}
        <h1>{{ todo.title }}</h1>
        상태: <code class="highlight">{% if todo.complete %}완료{% else %}대기중{% endif %}</code>
        {% if not todo.complete %}
          <a href="{% url 'todo_do' todo.id 0 %}"><button class="btn btn-primary btn-sm">정상 완료 처리</button></a>
          <a href="{% url 'todo_do' todo.id 1 %}"><button class="btn btn-primary btn-sm">연체 완료 처리</button></a>
        {% else %}
          <a href="{% url 'todo_undo' todo.id %}"><button class="btn btn-primary btn-sm">미완료 처리</button></a>
        {% endif %}</br>
        기록 페이지:
        {% if todo.daily_page %}
        <a href="{% url 'wiki_view_page' todo.daily_page %}">{{ todo.daily_page }}</a>
        {% else %}
        페이지 없음
        {% endif %}</br>
        {{ todo.get_markdown_content | wikify | safe }}
        <hr/>
        <a href="{% url 'todo_edit' todo.id %}"><button class="btn btn-info">할 일 수정</button></a>
        <a href="{% url 'todo_delete' todo.id %}"><button class="btn btn-danger">할 일 삭제</button></a>
    {% endfor %}
{% endblock %}